<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            [
                'category_id' => 1,
                'name' => 'Lipstick',
                'slug' => 'lipstick',
                'price' => 499.99,
                'stock' => 100,
                'description' => 'Premium matte lipstick',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Face Wash',
                'slug' => 'face-wash',
                'price' => 299.00,
                'stock' => 150,
                'description' => 'Refreshing daily face wash',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Moisturizer',
                'slug' => 'moisturizer',
                'price' => 699.00,
                'stock' => 80,
                'description' => 'Hydrating skin moisturizer',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Perfume',
                'slug' => 'perfume',
                'price' => 1999.00,
                'stock' => 40,
                'description' => 'Luxury fragrance perfume',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Shampoo',
                'slug' => 'shampoo',
                'price' => 399.00,
                'stock' => 120,
                'description' => 'Hair care shampoo',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'category_id' => 2,
                'name' => 'Wireless Headphones',
                'slug' => 'wireless-headphones',
                'price' => 2999.00,
                'stock' => 50,
                'description' => 'Bluetooth headphones',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Smart Watch',
                'slug' => 'smart-watch',
                'price' => 4999.00,
                'stock' => 60,
                'description' => 'Fitness smart watch',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Gaming Mouse',
                'slug' => 'gaming-mouse',
                'price' => 1499.00,
                'stock' => 90,
                'description' => 'RGB gaming mouse',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Mechanical Keyboard',
                'slug' => 'mechanical-keyboard',
                'price' => 3499.00,
                'stock' => 70,
                'description' => 'Mechanical gaming keyboard',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Bluetooth Speaker',
                'slug' => 'bluetooth-speaker',
                'price' => 2499.00,
                'stock' => 85,
                'description' => 'Portable bluetooth speaker',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'category_id' => 3,
                'name' => 'Men T-Shirt',
                'slug' => 'men-t-shirt',
                'price' => 799.00,
                'stock' => 200,
                'description' => 'Cotton round neck t-shirt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Women Hoodie',
                'slug' => 'women-hoodie',
                'price' => 1499.00,
                'stock' => 90,
                'description' => 'Warm casual hoodie',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Jeans',
                'slug' => 'jeans',
                'price' => 1299.00,
                'stock' => 110,
                'description' => 'Slim fit jeans',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Jacket',
                'slug' => 'jacket',
                'price' => 2499.00,
                'stock' => 45,
                'description' => 'Winter leather jacket',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Sneakers',
                'slug' => 'sneakers',
                'price' => 2999.00,
                'stock' => 75,
                'description' => 'Casual white sneakers',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'category_id' => 1,
                'name' => 'Nail Polish',
                'slug' => 'nail-polish',
                'price' => 199.00,
                'stock' => 140,
                'description' => 'Glossy nail polish',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'USB-C Charger',
                'slug' => 'usb-c-charger',
                'price' => 999.00,
                'stock' => 130,
                'description' => 'Fast charging adapter',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 3,
                'name' => 'Cap',
                'slug' => 'cap',
                'price' => 399.00,
                'stock' => 100,
                'description' => 'Stylish sports cap',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 2,
                'name' => 'Laptop Stand',
                'slug' => 'laptop-stand',
                'price' => 1799.00,
                'stock' => 55,
                'description' => 'Adjustable aluminum stand',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'category_id' => 1,
                'name' => 'Sunscreen',
                'slug' => 'sunscreen',
                'price' => 599.00,
                'stock' => 95,
                'description' => 'SPF 50 sunscreen lotion',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
